/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStudy {
  'id' : string,
  'client' : string,
  'title' : string,
  'summary' : string,
  'category' : string,
}
export interface ContactSubmission {
  'id' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Event {
  'id' : string,
  'title' : string,
  'date' : bigint,
  'language' : string,
  'registrationUrl' : string,
  'location' : string,
}
export interface Insight {
  'id' : string,
  'title' : string,
  'date' : bigint,
  'summary' : string,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createCaseStudy' : ActorMethod<[CaseStudy], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'createInsight' : ActorMethod<[Insight], undefined>,
  'deleteCaseStudy' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteInsight' : ActorMethod<[string], undefined>,
  'getAllCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllInsights' : ActorMethod<[], Array<Insight>>,
  'getCaseStudy' : ActorMethod<[string], CaseStudy>,
  'getEvent' : ActorMethod<[string], Event>,
  'getInsight' : ActorMethod<[string], Insight>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
  'updateCaseStudy' : ActorMethod<[string, CaseStudy], undefined>,
  'updateEvent' : ActorMethod<[string, Event], undefined>,
  'updateInsight' : ActorMethod<[string, Insight], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];