/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseStudy = IDL.Record({
  'id' : IDL.Text,
  'client' : IDL.Text,
  'title' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'language' : IDL.Text,
  'registrationUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const Insight = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createCaseStudy' : IDL.Func([CaseStudy], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'createInsight' : IDL.Func([Insight], [], []),
  'deleteCaseStudy' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteInsight' : IDL.Func([IDL.Text], [], []),
  'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
  'getCaseStudy' : IDL.Func([IDL.Text], [CaseStudy], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getInsight' : IDL.Func([IDL.Text], [Insight], ['query']),
  'submitContactForm' : IDL.Func([ContactSubmission], [], []),
  'updateCaseStudy' : IDL.Func([IDL.Text, CaseStudy], [], []),
  'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
  'updateInsight' : IDL.Func([IDL.Text, Insight], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseStudy = IDL.Record({
    'id' : IDL.Text,
    'client' : IDL.Text,
    'title' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'language' : IDL.Text,
    'registrationUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const Insight = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createCaseStudy' : IDL.Func([CaseStudy], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'createInsight' : IDL.Func([Insight], [], []),
    'deleteCaseStudy' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteInsight' : IDL.Func([IDL.Text], [], []),
    'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
    'getCaseStudy' : IDL.Func([IDL.Text], [CaseStudy], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getInsight' : IDL.Func([IDL.Text], [Insight], ['query']),
    'submitContactForm' : IDL.Func([ContactSubmission], [], []),
    'updateCaseStudy' : IDL.Func([IDL.Text, CaseStudy], [], []),
    'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
    'updateInsight' : IDL.Func([IDL.Text, Insight], [], []),
  });
};

export const init = ({ IDL }) => { return []; };