/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CaseStudy {
    id: string;
    client: string;
    title: string;
    summary: string;
    category: string;
}
export type Time = bigint;
export interface ContactSubmission {
    id: string;
    name: string;
    email: string;
    company: string;
    message: string;
    timestamp: Time;
}
export interface Insight {
    id: string;
    title: string;
    date: bigint;
    summary: string;
    category: string;
}
export interface Event {
    id: string;
    title: string;
    date: bigint;
    language: string;
    registrationUrl: string;
    location: string;
}
export interface backendInterface {
    createCaseStudy(caseStudy: CaseStudy): Promise<void>;
    createEvent(event: Event): Promise<void>;
    createInsight(insight: Insight): Promise<void>;
    deleteCaseStudy(id: string): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    deleteInsight(id: string): Promise<void>;
    getAllCaseStudies(): Promise<Array<CaseStudy>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllInsights(): Promise<Array<Insight>>;
    getCaseStudy(id: string): Promise<CaseStudy>;
    getEvent(id: string): Promise<Event>;
    getInsight(id: string): Promise<Insight>;
    submitContactForm(submission: ContactSubmission): Promise<void>;
    updateCaseStudy(id: string, updatedCaseStudy: CaseStudy): Promise<void>;
    updateEvent(id: string, updatedEvent: Event): Promise<void>;
    updateInsight(id: string, updatedInsight: Insight): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCaseStudy(arg0: CaseStudy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCaseStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCaseStudy(arg0);
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async createInsight(arg0: Insight): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInsight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInsight(arg0);
            return result;
        }
    }
    async deleteCaseStudy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCaseStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCaseStudy(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteInsight(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInsight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInsight(arg0);
            return result;
        }
    }
    async getAllCaseStudies(): Promise<Array<CaseStudy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCaseStudies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCaseStudies();
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return result;
        }
    }
    async getAllInsights(): Promise<Array<Insight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInsights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInsights();
            return result;
        }
    }
    async getCaseStudy(arg0: string): Promise<CaseStudy> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseStudy(arg0);
            return result;
        }
    }
    async getEvent(arg0: string): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return result;
        }
    }
    async getInsight(arg0: string): Promise<Insight> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsight(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async updateCaseStudy(arg0: string, arg1: CaseStudy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseStudy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseStudy(arg0, arg1);
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
    async updateInsight(arg0: string, arg1: Insight): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInsight(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInsight(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
